create_boot_directory

build {
    core
    init
    app/fss_test
}

install_config {
<config verbose="yes">
<parent-provides>
<service name="LOG"/>
<service name="ROM"/>
<service name="RAM"/>
<service name="PD"/>
<service name="CPU"/>
</parent-provides>
<default-route>
<any-service> <parent/> </any-service>
</default-route>
<start name="fss_test" caps="100">
<resource name="RAM" quantum="8M"/>
</start>
</config>
}

build_boot_image {
    core
    init
    fss_test
}

run_genode_until {--- \[fss_test\] Component started successfully! ---.*} 60
