create_boot_directory

build {
    init
    app/fss_test
    timer
    lib/ld
    lib/libc
    lib/vfs
}

install_config {
    <config>
        <parent-provides>
            <service name="CPU"/>
            <service name="IO_MEM"/>
            <service name="IO_PORT"/>
            <service name="IRQ"/>
            <service name="LOG"/>
            <service name="PD"/>
            <service name="RM"/>
            <service name="ROM"/>
        </parent-provides>

        <default-route>
            <any-service> <parent/> <any-child/> </any-service>
        </default-route>

        <start name="timer" caps="100">
            <resource name="RAM" quantum="4M"/>
            <provides><service name="Timer"/></provides>
        </start>

        <start name="fss_test" caps="200">
            <resource name="RAM" quantum="32M"/>
            <config>
                <libc stdout="/dev/log" stderr="/dev/log"/>
                <vfs>
                    <dir name="dev"> <log/> </dir>
                    <ram/>
                </vfs>
            </config>
        </start>
    </config>
}

build_boot_image [build_artifacts]

append qemu_args " -m 512M "

run_genode_until "--- MY APP FSS Test Finished ---\n" 30s
