create_boot_directory

# استفاده از مسیر مطلقِ روتِ پروژه برای پیدا کردن دقیق پوشه host_data
exec tar cf bin/my_host_files.tar -C [genode_dir]/repos/genode-embedded-nova/src/app/fss_test host_data

build {
    init
    app/fss_test
    timer
    lib/ld
    lib/libc
    lib/vfs
}

install_config {
    <config>
        <parent-provides>
            <service name="CPU"/>
            <service name="IO_MEM"/>
            <service name="IO_PORT"/>
            <service name="IRQ"/>
            <service name="LOG"/>
            <service name="PD"/>
            <service name="RM"/>
            <service name="ROM"/>
        </parent-provides>

        <default-route>
            <any-service> <parent/> <any-child/> </any-service>
        </default-route>

        <start name="timer" caps="100">
            <resource name="RAM" quantum="4M"/>
            <provides><service name="Timer"/></provides>
        </start>

        <!-- معرفی فایل آرشیو به عنوان یک ماژول ROM -->
        <rom name="my_host_files.tar"/>

        <start name="fss_test" caps="200">
            <resource name="RAM" quantum="32M"/>
            <config>
                <libc stdout="/dev/log" stderr="/dev/log"/>
                <vfs>
                    <dir name="dev"> <log/> </dir>
                    <!-- خواندن محتویات از فایل tar متصل شده -->
                    <tar name="my_host_files.tar"/>
                </vfs>
            </config>
        </start>
    </config>
}

# اضافه کردن فایل tar به تصاویر بوت ماشین مجازی
build_boot_image [concat [build_artifacts] { my_host_files.tar }]

append qemu_args " -m 512M "

run_genode_until "--- Host File Read Test Finished ---\n" 30s
